/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
 * Generated on: 03-Jun-2018 15:01:55
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 21
 * Denominator Length  : 21
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\include\tmwtypes.h 
 */
const int NL = 21;
const double NUM[21] = {
  2.490217764598e-07,4.980435529197e-06,4.731413752737e-05,0.0002838848251642,
   0.001206510506948, 0.003860833622233, 0.009652084055583,  0.01930416811117,
    0.03136927318065,  0.04182569757419,  0.04600826733161,  0.04182569757419,
    0.03136927318065,  0.01930416811117, 0.009652084055583, 0.003860833622233,
   0.001206510506948,0.0002838848251642,4.731413752737e-05,4.980435529197e-06,
  2.490217764598e-07
};
const int DL = 21;
const double DEN[21] = {
                   1,   -4.016678255516,    10.15969963161,   -18.05144745214,
      25.09330982256,    -28.1374605527,    26.21971142087,   -20.55097364465,
      13.69224959049,   -7.783462828603,    3.782525568614,   -1.568281904371,
     0.5523776736727,  -0.1639552730011,  0.04053180540989,-0.008201450656376,
   0.001324521130835,-0.000164300711896,1.470916543583e-05,-8.464337032562e-07,
  2.352308300535e-08
};
